[ { resourceId: 'octo153',
    title: 'CRB Business Solutions: jobs board',
    url: 'https://www.cbrsolutions.org.uk/jobs-board',
    summary: 'Job listings in the charity and business sector.',
    journalMessage: 'This might help you with your job search: \n\nhttps://www.cbrsolutions.org.uk/jobs-board\n\nIt\'s a website where you can search for jobs in the charity and business sector.',
    category: [ 'searching for work', 'work search', 'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo154',
    title: 'Reed: CV builder',
    url: 'https://www.reed.co.uk/cvbuilder',
    summary: 'A tool for building a CV in 4 steps.',
    journalMessage: 'This tool can help you with your CV:\n\nhttps://www.reed.co.uk/cvbuilder\n\nYou\'ll need to register, and after that it will guide you through making a new CV in 4 steps.',
    category: 
     [ 'CVs, cover letters and interviews',
       'work search',
       'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo155',
    title: 'GOV.UK: Get into teaching',
    url: 'https://getintoteaching.education.gov.uk',
    summary: 'Advice and information on teaching from the Department for Education - eligibility, funding and salary, how to apply, teaching events, and more.',
    journalMessage: 'This guide has useful advice on how to get into teaching:\n\nhttps://getintoteaching.education.gov.uk\n\nIt includes information about eligibility, funding and salary, how to apply, and teaching events.',
    category: [ 'searching for work', 'work search', 'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo156',
    title: 'Reed',
    url: 'http://www.reed.co.uk',
    summary: 'A job search website with career advice, including a CV builder and interview tips.',
    journalMessage: 'This might help you with your job search: \n\nhttp://www.reed.co.uk\n\nIt\'s a website where you can search for jobs and get career advice.',
    category: [ 'searching for work', 'work search', 'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo157',
    title: 'No Desire To Retire',
    url: 'http://nodesiretoretire.com',
    summary: 'A job search website aimed at people over the age of 50.',
    journalMessage: 'Here\'s a website you might find useful - it lists jobs aimed at people over the age of 50 looking for work:\n\nhttp://nodesiretoretire.com',
    category: 
     [ 'searching for work',
       'work search',
       'research',
       'other support' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo158',
    title: 'Hays',
    url: 'https://www.hays.co.uk',
    summary: 'A recruiter with job listings.',
    journalMessage: 'This might help you with your job search:\n\nhttps://www.hays.co.uk\n\nIt\'s a recruiter, and you can use its website to find job listings.',
    category: [ 'searching for work', 'work search', 'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo159',
    title: 'GOV.UK: Find an apprenticeship',
    url: 'https://www.findapprenticeship.service.gov.uk/apprenticeshipsearch',
    summary: 'A GOV.UK tool for searching for apprenticeships in England. It has listings and information on how to apply.',
    journalMessage: 'This might help you with your search for an apprenticeship:\n\nhttps://www.findapprenticeship.service.gov.uk/apprenticeshipsearch\n\nIt has apprenticeship listings and information on how to apply.',
    category: 
     [ 'searching for work',
       'work search',
       'research',
       'apprenticeships' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo160',
    title: 'GOV.UK: Access to Work',
    url: 'https://www.gov.uk/access-to-work',
    summary: 'A GOV.UK guide explaining how to get help at work if you’re disabled or have a health condition (Access to Work) - eligibility, how it works, how to apply, and more.',
    journalMessage: 'To find out how to get help at work if you\'re disabled or have a health condition (Access to Work), this guide should have everything you need:\n\nhttps://www.gov.uk/access-to-work\n\nIt includes information on eligibility, how it works, and how to apply.',
    category: 
     [ 'health, mental health and wellbeing',
       'preparing for work',
       'other support',
       'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo161',
    title: 'GOV.UK: Apply for free school meals',
    url: 'https://www.gov.uk/apply-free-school-meals',
    summary: 'A GOV.UK guide explaining how to apply for free school meals.',
    journalMessage: 'You might be able to apply for free school meals. To find out how, this guide should have everything you need:\n\nhttps://www.gov.uk/apply-free-school-meals',
    category: [ 'preparing for work', 'other support', 'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo162',
    title: 'GOV.UK: Benefit cap calculator',
    url: 'https://www.gov.uk/benefit-cap-calculator',
    summary: 'A GOV.UK calculator that finds an estimate of how much your benefit might be capped.',
    journalMessage: 'To find out how much your benefit might be capped, you can use this calculator: \n\nhttps://www.gov.uk/benefit-cap-calculator',
    category: [ 'preparing for work', 'other support', 'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo163',
    title: 'GOV.UK: Benefits calculators',
    url: 'https://www.gov.uk/benefits-calculators',
    summary: 'A GOV.UK guide explaining how to use benefits calculators.',
    journalMessage: 'To find out how to use benefits calculators, this guide should have everything you need:\n\nhttps://www.gov.uk/benefits-calculators',
    category: [ 'preparing for work', 'other support', 'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo164',
    title: 'GOV.UK: Care to learn',
    url: 'https://www.gov.uk/care-to-learn',
    summary: 'A GOV.UK guide explaining Care to Learn - a scheme that helps with childcare costs while studying.',
    journalMessage: 'The Care to Learn scheme could help you with childcare costs while you study. To find out more about the scheme, this guide should have everything you need: \n\nhttps://www.gov.uk/care-to-learn',
    category: [ 'preparing for work', 'other support', 'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo165',
    title: 'GOV.UK: Childcare calculator',
    url: 'https://www.gov.uk/childcare-calculator',
    summary: 'A GOV.UK calculator that checks what help you could get with childcare costs.',
    journalMessage: 'You might be able to get help with childcare costs. To find out how much you could get, you can use this calculator: \n\nhttps://www.gov.uk/childcare-calculator',
    category: [ 'preparing for work', 'other support', 'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo166',
    title: 'Reed: CV templates and tips',
    url: 'https://www.reed.co.uk/career-advice/cv-templates-and-tips',
    summary: 'Advice on CVs, including templates and tips.',
    journalMessage: 'This website can help you work on your CV:\n\nhttps://www.reed.co.uk/career-advice/cv-templates-and-tips\n\nIt has CV templates and tips.',
    category: 
     [ 'CVs, cover letters and interviews',
       'work search',
       'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo167',
    title: 'Rethink Mental Illness',
    url: 'https://www.rethink.org',
    summary: 'A charity that provides advice and information to everyone affected by mental health problems.',
    journalMessage: 'Take a look at Rethink Mental Illness - they have advice that helps anyone affected by mental health problems:\n\nhttps://www.rethink.org',
    category: [ 'health, mental health and wellbeing' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo168',
    title: 'NHS in England: help with health costs',
    url: 'www.nhs.uk/healthcosts',
    summary: 'Information about help with health costs at the NHS in England.',
    journalMessage: 'You may be able to get help with NHS costs. To find out how, this guide should have everything you need:\n\nwww.nhs.uk/healthcosts',
    category: [ 'health, mental health and wellbeing' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo169',
    title: 'Age UK',
    url: 'http://www.ageuk.org.uk',
    summary: 'A charity that helps people know their rights as they grow older and make the best choices for later life.',
    journalMessage: 'Take a look at Age UK - they have advice that helps people as they get older:\n\nhttp://www.ageuk.org.uk\n\nThe website includes information on your rights and how to make the best choices for later life.',
    category: [ 'other support', 'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo170',
    title: 'Creative and Cultural Skills',
    url: 'https://ccskills.org.uk',
    summary: 'A charity that helps young people to work and learn in the creative industries - career advice, apprenticeships, activities, and more.',
    journalMessage: 'Take a look at Creative and Cultural Skills - they help young people to find work and learn in creative industries:\n\nhttps://ccskills.org.uk\n\nThe website includes career advice, apprenticeships and activities.',
    category: 
     [ 'skills, training and qualifications',
       'apprenticeships',
       'research' ],
    groups: [ '' ],
    sector: { '': '' } },
  { resourceId: 'octo171',
    title: 'Glassdoor: cover letters',
    url: 'https://www.glassdoor.com/blog/tag/cover-letters',
    summary: 'Advice on cover letters.',
    journalMessage: 'This tool can help you work on your cover letters:\n\nhttps://www.glassdoor.com/blog/tag/cover-letters',
    category: 
     [ 'CVs, cover letters and interviews',
       'work search',
       'research' ],
    groups: [ '' ],
    sector: { '': '' } } ]
